version: '3.1'

services:
    goproxy:
        build: ./eensywebproxy
        volumes: 
            - "./proxy:/usr/src/eensy"
            - "./nginx/data:/usr/src/eensy/web/data"
            - "./nginx/pages:/usr/src/eensy/web/pages"
            - "/var/log/eensyproxy:/var/log/eensyproxy"
        environment: 
            - LOGF=/var/log/eensyproxy/proxy.log
            - RZPKEY=rzp_test_Z4AumzgwmBpgQv
            - RZPSECRET=TQXlGbKAXteB8UYhzWqgrB2A
        links:
            - "mongo"
        entrypoint: ["/usr/bin/eensy/webproxy"]
    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - "./nginx:/var/www/eensyweb"
            - "/var/log/nginx:/var/log/nginx"
        links: 
            - "goproxy"
    srvmongo:
        image: mongo:4.2-bionic
        ports:
            - 37017:27017
        volumes: 
        - /data/eensyweb/db:/data/db
        tty: true
        stdin_open: true
    
